# Generated by Django 4.0.5 on 2022-06-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortenmodel',
            name='short_url',
            field=models.CharField(max_length=15),
        ),
    ]
