# Generated by Django 4.0.5 on 2022-06-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_urlshortenmodel_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortenmodel',
            name='short_url',
            field=models.CharField(max_length=50),
        ),
    ]
